
// namespace Throw1{
//     public class Person{
//         public readonly int num=3;
      
//         public void exception1(){
//             try{
//            var x= num/0;
//             }catch(Exception ex)when(ex.Message.Contains("Attempted")){
//                 Console.WriteLine(ex);
//                 throw new Exception("rethroe",ex);
//             }
//         }
        
       
//     }
//      public class A{
//         public static void Main(){
//             Person p = new();
//             p.exception1();
//         }
//     }
// }